import { canUseDjFeatures, planAllowsDjFeatures } from '../utils/djPrefs';

/** @typedef {import('react').MutableRefObject} MutableRefObject */

/**
 * Outlet context value shared across pages (player, library, search, …).
 */
export function buildPlayerOutletContext({
  transport,
  currentTrackId,
  playingTrackId,
  isPlaying,
  isLoading,
  likedTracks,
  toggleLike,
  handleDownload,
  libraryRevision,
  playbackQuality,
  setPlaybackQuality,
  defaultPlaybackQuality,
  setDefaultPlaybackQuality,
  autoPlaybackQuality,
  setAutoPlaybackQuality,
  theme,
  setTheme,
  audioRef,
  visualizerEnabled,
  setVisualizerEnabled,
  lang,
  setLang,
  t,
  downloadedTracks,
  playlist,
  effectivePlan,
  djAnalysisEnabled,
  setDjAnalysisEnabled,
}) {
  return {
    togglePlay: transport.togglePlay,
    playQueue: transport.playQueue,
    playShuffledQueue: transport.playShuffledQueue,
    currentTrackId,
    playingTrackId,
    isPlaying,
    isLoading,
    likedTracks,
    toggleLike,
    handleDownload,
    libraryRevision,
    playbackQuality,
    setPlaybackQuality,
    defaultPlaybackQuality,
    setDefaultPlaybackQuality,
    autoPlaybackQuality,
    setAutoPlaybackQuality,
    theme,
    setTheme,
    audioRef,
    visualizerEnabled,
    setVisualizerEnabled,
    lang,
    setLang,
    t,
    downloadedTracks,
    playlist,
    startTrackRadio: transport.startTrackRadio,
    effectivePlan,
    djAnalysisEnabled,
    setDjAnalysisEnabled,
    djFeaturesAvailable: planAllowsDjFeatures(effectivePlan),
    djFeaturesActive: canUseDjFeatures(effectivePlan, djAnalysisEnabled),
  };
}
